### ISSUE TITLE
CZ20 Badge loops on "Generating a spoken name for app" with random beep afterwards

### ISSUE THREAD

**Issue by renssies** [badgeteam/website-docs#7]
So I had a total of 8 apps installed. Installing any new app causes the launcher to get stuck in a loop saying "Generating a spoken name for app" with a random beep after it. See my video in Discord: https://cdn.discordapp.com/attachments/330694334808719361/735242659261841558/video0.mov

**Firmware Version:** 20072104

**Installed apps:**
- Synthesizer
- fourinarow
- bnr_radio
- cybertyper
- bubblewrap
- soundboard
- pride
- simon_says_cz20
- digital_cricket
- homescreenota

**Files:**

![Screen Shot 2020-07-22 at 10 23 11](https://user-images.githubusercontent.com/830094/88153185-5c14ef00-cc05-11ea-9fe3-4584db95344e.png)
![Screen Shot 2020-07-22 at 10 24 05](https://user-images.githubusercontent.com/830094/88153290-8070cb80-cc05-11ea-8141-c67543924dee.png)
![Screen Shot 2020-07-22 at 10 23 58](https://user-images.githubusercontent.com/830094/88153292-81096200-cc05-11ea-8f30-c4e1b0dbf80f.png)

**SD Card installed:** Yes, 16GB unbranded from Taiwain. Works in Soundboard app

**Terminal output:**
```
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
>>> Preparing TTS:  Simon Says CZ20
Starting app 'launcher'...
```

If you need more information you can reach me as "renssies" on most messaging platforms including Discord and Telegram

**Comment by renssies** [comment]
We found that it is related to having an SD card in the badge, if I remove the SD card, then power the badge it can successfully generate the names and doesn't beep anymore. 

After that can put in the SD card and power it again and it still doesn't beep anymore.

**Comment by renzenicolai** [comment]
Not related to this repo.
